/** @type {import('tailwindcss').Config} */

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: "1rem",
        sm: "2rem",
        lg: "4rem",
        xl: "6rem",
        "2xl": "8rem",
      },
    },
    extend: {
      colors: {
        vintage: {
          brown: "#3E2723",
          brownLight: "#5D4037",
          brownDark: "#2C1810",
          gold: "#D4AF37",
          goldLight: "#E8C96A",
          goldDark: "#B8941F",
          paper: "#F5E6C8",
          paperDark: "#E8D4A8",
          paperLight: "#FAF0D7",
          brick: "#B7410E",
          brickLight: "#D46233",
          moss: "#2F4538",
          mossLight: "#4A6B5A",
          ink: "#2D1F14",
          inkLight: "#4A3728",
        },
      },
      fontFamily: {
        display: ['"Playfair Display"', '"Noto Serif SC"', 'Georgia', 'serif'],
        serif: ['"Noto Serif SC"', '"Lora"', 'Georgia', 'serif'],
        body: ['"Lora"', '"Noto Serif SC"', 'Georgia', 'serif'],
      },
      backgroundImage: {
        'noise': "url(\"data:image/svg+xml,%3Csvg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noiseFilter'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noiseFilter)' opacity='0.08'/%3E%3C/svg%3E\")",
        'vintage-gradient': 'linear-gradient(135deg, #3E2723 0%, #5D4037 50%, #2C1810 100%)',
        'paper-texture': 'linear-gradient(180deg, #FAF0D7 0%, #F5E6C8 100%)',
      },
      boxShadow: {
        'vintage': '0 4px 20px rgba(62, 39, 35, 0.25), 0 2px 6px rgba(62, 39, 35, 0.15)',
        'vintage-lg': '0 10px 40px rgba(62, 39, 35, 0.3), 0 4px 12px rgba(62, 39, 35, 0.2)',
        'gold-glow': '0 0 20px rgba(212, 175, 55, 0.3), 0 0 40px rgba(212, 175, 55, 0.1)',
        'inset-paper': 'inset 0 2px 4px rgba(62, 39, 35, 0.1)',
      },
      borderColor: {
        'gold': '#D4AF37',
        'gold-light': '#E8C96A',
      },
      animation: {
        'spin-slow': 'spin 20s linear infinite',
        'spin-pause': 'spin 8s linear infinite',
        'fade-in-up': 'fadeInUp 0.6s ease-out',
        'fade-in': 'fadeIn 0.8s ease-out',
        'float': 'float 6s ease-in-out infinite',
        'glitch-flicker': 'glitchFlicker 0.15s infinite',
        'year-scanlines': 'scanlines 8s linear infinite',
        'tv-noise': 'tvNoise 0.5s steps(10) infinite',
        'tape-stutter': 'tapeStutter 0.3s infinite',
        'cd-skip': 'cdSkip 2s infinite',
        'radio-static': 'radioStatic 0.2s infinite',
        'text-glitch': 'textGlitch 2s infinite',
        'window-shake': 'windowShake 0.5s',
        'bsod-blink': 'bsodBlink 1s infinite',
        'danmaku-slow': 'danmakuMove 18s linear forwards',
        'danmaku-normal': 'danmakuMove 14s linear forwards',
        'danmaku-fast': 'danmakuMove 10s linear forwards',
        'popup-bounce-in': 'popupBounceIn 0.4s cubic-bezier(0.34, 1.56, 0.64, 1)',
        'concert-danmaku': 'concertDanmaku 12s linear forwards',
        'gift-float': 'giftFloat 3s ease-out forwards',
        'gift-pulse': 'giftPulse 0.8s ease-in-out infinite',
        'stage-glow': 'stageGlow 3s ease-in-out infinite',
        'crowd-wave': 'crowdWave 2s ease-in-out infinite',
      },
      keyframes: {
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        glitchFlicker: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.3' },
        },
        scanlines: {
          '0%': { transform: 'translateY(0)' },
          '100%': { transform: 'translateY(100%)' },
        },
        tvNoise: {
          '0%': { transform: 'translate(0, 0)' },
          '10%': { transform: 'translate(-5%, -5%)' },
          '20%': { transform: 'translate(5%, 5%)' },
          '30%': { transform: 'translate(-3%, 3%)' },
          '40%': { transform: 'translate(3%, -3%)' },
          '50%': { transform: 'translate(-2%, 2%)' },
          '60%': { transform: 'translate(2%, -2%)' },
          '70%': { transform: 'translate(-1%, 1%)' },
          '80%': { transform: 'translate(1%, -1%)' },
          '90%': { transform: 'translate(-0.5%, 0.5%)' },
          '100%': { transform: 'translate(0, 0)' },
        },
        tapeStutter: {
          '0%, 100%': { transform: 'translateX(0)', filter: 'saturate(1)' },
          '25%': { transform: 'translateX(3px)', filter: 'saturate(2)' },
          '50%': { transform: 'translateX(-3px)', filter: 'saturate(0.5)' },
          '75%': { transform: 'translateX(2px)', filter: 'saturate(1.5)' },
        },
        cdSkip: {
          '0%, 90%, 100%': { transform: 'translateX(0)', filter: 'none' },
          '92%': { transform: 'translateX(-10px)', filter: 'blur(2px)' },
          '94%': { transform: 'translateX(10px)', filter: 'blur(1px)' },
          '96%': { transform: 'translateX(-5px)', filter: 'blur(3px)' },
          '98%': { transform: 'translateX(5px)', filter: 'blur(1px)' },
        },
        radioStatic: {
          '0%, 100%': { filter: 'none' },
          '33%': { filter: 'contrast(1.5) saturate(0.8)' },
          '66%': { filter: 'contrast(0.8) saturate(1.2)' },
        },
        textGlitch: {
          '0%, 90%, 100%': { transform: 'translate(0)', filter: 'none', opacity: '1' },
          '92%': { transform: 'translate(2px, 1px)', filter: 'hue-rotate(90deg)', opacity: '0.8' },
          '94%': { transform: 'translate(-1px, -2px)', filter: 'hue-rotate(-90deg)', opacity: '0.9' },
          '96%': { transform: 'translate(1px, 2px)', filter: 'hue-rotate(180deg)', opacity: '0.7' },
          '98%': { transform: 'translate(-2px, -1px)', filter: 'hue-rotate(-45deg)', opacity: '1' },
        },
        windowShake: {
          '0%, 100%': { transform: 'translate(0, 0)' },
          '10%': { transform: 'translate(-5px, -5px)' },
          '20%': { transform: 'translate(5px, 5px)' },
          '30%': { transform: 'translate(-5px, 5px)' },
          '40%': { transform: 'translate(5px, -5px)' },
          '50%': { transform: 'translate(-3px, -3px)' },
          '60%': { transform: 'translate(3px, 3px)' },
          '70%': { transform: 'translate(-3px, 3px)' },
          '80%': { transform: 'translate(3px, -3px)' },
          '90%': { transform: 'translate(-1px, -1px)' },
        },
        bsodBlink: {
          '0%, 50%, 100%': { opacity: '1' },
          '25%, 75%': { opacity: '0.7' },
        },
        danmakuMove: {
          '0%': { transform: 'translateX(100vw)', opacity: '0' },
          '5%': { opacity: '1' },
          '95%': { opacity: '1' },
          '100%': { transform: 'translateX(-100%)', opacity: '0' },
        },
        popupBounceIn: {
          '0%': { transform: 'scale(0.3)', opacity: '0' },
          '50%': { transform: 'scale(1.05)' },
          '70%': { transform: 'scale(0.95)' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        concertDanmaku: {
          '0%': { transform: 'translateX(100%)', opacity: '0' },
          '5%': { opacity: '1' },
          '95%': { opacity: '1' },
          '100%': { transform: 'translateX(-150%)', opacity: '0' },
        },
        giftFloat: {
          '0%': { transform: 'translateY(20px) scale(0.5)', opacity: '0' },
          '20%': { transform: 'translateY(0) scale(1.2)', opacity: '1' },
          '50%': { transform: 'translateY(-30px) scale(1)', opacity: '1' },
          '100%': { transform: 'translateY(-80px) scale(0.8)', opacity: '0' },
        },
        giftPulse: {
          '0%, 100%': { transform: 'scale(1)', filter: 'drop-shadow(0 0 8px rgba(212, 175, 55, 0.6))' },
          '50%': { transform: 'scale(1.15)', filter: 'drop-shadow(0 0 20px rgba(212, 175, 55, 0.9))' },
        },
        stageGlow: {
          '0%, 100%': { boxShadow: '0 0 40px rgba(212, 175, 55, 0.3), 0 0 80px rgba(183, 65, 14, 0.2)' },
          '50%': { boxShadow: '0 0 80px rgba(212, 175, 55, 0.5), 0 0 120px rgba(183, 65, 14, 0.35)' },
        },
        crowdWave: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-6px)' },
        },
      },
    },
  },
  plugins: [],
};
